package com.plexoncrates.command;

import com.plexoncrates.config.ConfigManager;
import com.plexoncrates.core.PlexonCrates;
import com.plexoncrates.crate.Crate;
import com.plexoncrates.crate.RewardAction;
import com.plexoncrates.crate.RewardActionType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import org.bukkit.Bukkit;
import org.bukkit.block.Block;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public final class CrateCommand implements CommandExecutor,TabCompleter {
    private final PlexonCrates plugin;private final ConfigManager config;public CrateCommand(PlexonCrates plugin,ConfigManager config){this.plugin=plugin;this.config=config;}
    @Override public boolean onCommand(@NotNull CommandSender sender,@NotNull Command command,@NotNull String label,@NotNull String[] args){try{if(args.length==0){Player player=player(sender);require(player,"plexoncrates.use");plugin.gui().openPlayerMenu(player);return true;}String sub=args[0].toLowerCase(Locale.ROOT);switch(sub){case"admin"->admin(sender,args);case"preview"->preview(sender,args);case"open"->open(sender,args);case"claims"->claims(sender,args);case"link"->link(sender,args);case"unlink"->unlink(sender);case"key"->key(sender,args);case"reward"->reward(sender,args);case"reload"->reload(sender);case"help"->help(sender);default->help(sender);}}catch(CommandFailure failure){sender.sendMessage(config.prefix()+"§c"+failure.getMessage());}catch(Exception error){sender.sendMessage(config.prefix()+"§c"+(error.getMessage()==null?error.getClass().getSimpleName():error.getMessage()));plugin.getLogger().log(java.util.logging.Level.WARNING,"Command /"+label+" "+String.join(" ",args)+" failed",error);}return true;}
    private void admin(CommandSender sender,String[] args){Player player=player(sender);require(player,"plexoncrates.admin.gui");if(args.length>=3&&args[1].equalsIgnoreCase("create")){Crate created=plugin.crates().create(args[2]);plugin.gui().openCrateEditor(player,created);return;}plugin.gui().openAdmin(player);}private void preview(CommandSender sender,String[] args){Player player=player(sender);require(player,"plexoncrates.preview");plugin.gui().openPreview(player,crate(args,1));}private void open(CommandSender sender,String[] args){Player player=player(sender);require(player,"plexoncrates.open");Crate crate=crate(args,1);String mode=args.length>=3?args[2].toLowerCase(Locale.ROOT):"virtual";if(mode.equals("physical"))plugin.openings().openPhysical(player,crate,player.getLocation());else plugin.openings().openVirtual(player,crate);}private void claims(CommandSender sender,String[] args){Player player=player(sender);require(player,"plexoncrates.use");int page=args.length>=2?Math.max(0,integer(args[1],"page")-1):0;plugin.gui().openClaims(player,page);}
    private void link(CommandSender sender,String[] args){Player player=player(sender);require(player,"plexoncrates.admin.link");Crate crate=crate(args,1);Block block=player.getTargetBlockExact(6);if(block==null||block.getType().isAir())throw new CommandFailure("Look at a chest, barrel or other tile-state block.");try{plugin.crates().link(block,crate.id());player.sendMessage(config.message("linked","crate",crate.id()));}catch(IllegalArgumentException error){if(error.getMessage()!=null&&error.getMessage().contains("TileState"))player.sendMessage(config.message("tile-required"));else throw error;}}private void unlink(CommandSender sender){Player player=player(sender);require(player,"plexoncrates.admin.link");Block block=player.getTargetBlockExact(6);if(block==null||block.getType().isAir())throw new CommandFailure("Look at a linked crate block.");Optional<String> removed=plugin.crates().unlink(block);if(removed.isEmpty())throw new CommandFailure("That block is not linked to a crate.");player.sendMessage(config.message("unlinked"));}
    private void key(CommandSender sender,String[] args){require(sender,"plexoncrates.admin.keys");if(args.length<5)throw new CommandFailure("Usage: /crates key <give|physical> <player> <crate> <amount>");String action=args[1].toLowerCase(Locale.ROOT);Player target=Bukkit.getPlayerExact(args[2]);if(target==null)throw new CommandFailure("That player must be online.");Crate crate=plugin.crates().find(args[3]).orElseThrow(()->new CommandFailure("Unknown crate: "+args[3]));int amount=positive(args[4],100000);if(action.equals("physical")){givePhysical(target,crate,amount);sender.sendMessage(config.prefix()+"§aGranted §f"+amount+"x "+crate.id()+" §aphysical key(s) to §f"+target.getName()+"§a.");return;}if(!action.equals("give"))throw new CommandFailure("Key action must be give or physical.");plugin.keys().grantVirtual(target.getUniqueId(),crate,amount).whenComplete((balance,error)->Bukkit.getScheduler().runTask(plugin,()->{if(error!=null)sender.sendMessage(config.prefix()+"§cVirtual key grant failed.");else sender.sendMessage(config.message("key-granted","amount",Integer.toString(amount),"crate",crate.id(),"player",target.getName()));}));}
    private void reward(CommandSender sender,String[] args){require(sender,"plexoncrates.admin.rewards");if(args.length<2)throw new CommandFailure("Usage: /crates reward <add|remove|weight|action> ...");String action=args[1].toLowerCase(Locale.ROOT);switch(action){case"add"->{Player player=player(sender);if(args.length<4)throw new CommandFailure("Usage: /crates reward add <crate> <weight>");Crate crate=crate(args,2);int weight=positive(args[3],Integer.MAX_VALUE);ItemStack held=player.getInventory().getItemInMainHand();if(held.getType().isAir())throw new CommandFailure("Hold the exact reward item in your main hand.");var reward=plugin.crates().addCapturedReward(crate.id(),held,weight);sender.sendMessage(config.prefix()+"§aAdded reward §f"+reward.id()+" §awith weight §f"+reward.weight()+"§a.");}case"remove"->{if(args.length<4)throw new CommandFailure("Usage: /crates reward remove <crate> <reward>");Crate crate=crate(args,2);plugin.crates().removeReward(crate.id(),args[3]);sender.sendMessage(config.prefix()+"§aRemoved reward §f"+args[3]+"§a.");}case"weight"->{if(args.length<5)throw new CommandFailure("Usage: /crates reward weight <crate> <reward> <weight>");Crate crate=crate(args,2);int weight=nonNegative(args[4],Integer.MAX_VALUE);plugin.crates().setRewardWeight(crate.id(),args[3],weight);sender.sendMessage(config.prefix()+"§aUpdated reward weight to §f"+weight+"§a.");}case"action"->rewardAction(sender,args);default->throw new CommandFailure("Reward action must be add, remove, weight or action.");}}
    private void rewardAction(CommandSender sender,String[] args){if(args.length<5)throw new CommandFailure("Usage: /crates reward action <crate> <reward> <ITEM|COMMAND|MESSAGE|SOUND> [value]");Crate crate=crate(args,2);String rewardId=args[3];RewardActionType type;try{type=RewardActionType.valueOf(args[4].toUpperCase(Locale.ROOT));}catch(IllegalArgumentException error){throw new CommandFailure("Action type must be ITEM, COMMAND, MESSAGE or SOUND.");}RewardAction rewardAction;if(type==RewardActionType.ITEM){Player player=player(sender);ItemStack held=player.getInventory().getItemInMainHand();rewardAction=held.getType().isAir()?new RewardAction(type,"",null):new RewardAction(type,"",held.clone());}else{if(args.length<6)throw new CommandFailure("This action type requires a value.");rewardAction=new RewardAction(type,String.join(" ",Arrays.copyOfRange(args,5,args.length)),null);}plugin.crates().addRewardAction(crate.id(),rewardId,rewardAction);sender.sendMessage(config.prefix()+"§aAdded §f"+type+" §aaction to §f"+rewardId+"§a.");}
    private void reload(CommandSender sender){require(sender,"plexoncrates.admin.reload");plugin.reloadPlugin();sender.sendMessage(config.message("reload-complete"));}private void givePhysical(Player target,Crate crate,int amount){int remaining=amount;ItemStack template=crate.keyItem();while(remaining>0){ItemStack stack=template.clone();int give=Math.min(stack.getMaxStackSize(),remaining);stack.setAmount(give);remaining-=give;target.getInventory().addItem(stack).values().forEach(leftover->target.getWorld().dropItemNaturally(target.getLocation(),leftover));}}
    private Crate crate(String[] args,int index){if(args.length<=index)throw new CommandFailure("A crate ID is required.");return plugin.crates().find(args[index]).orElseThrow(()->new CommandFailure("Unknown crate: "+args[index]));}private Player player(CommandSender sender){if(sender instanceof Player player)return player;throw new CommandFailure("This action can only be used by a player.");}private static void require(CommandSender sender,String permission){if(!sender.hasPermission(permission)&&!sender.hasPermission("plexoncrates.admin"))throw new CommandFailure("You do not have permission to do that.");}private static int positive(String raw,int maximum){int value=integer(raw,"number");if(value<1||value>maximum)throw new CommandFailure("Number must be between 1 and "+maximum+".");return value;}private static int nonNegative(String raw,int maximum){int value=integer(raw,"number");if(value<0||value>maximum)throw new CommandFailure("Number must be between 0 and "+maximum+".");return value;}private static int integer(String raw,String label){try{return Integer.parseInt(raw);}catch(NumberFormatException error){throw new CommandFailure("Invalid "+label+": "+raw);}}
    private void help(CommandSender sender){sender.sendMessage(config.prefix()+"§6§lCommands");sender.sendMessage("§e/crates §7- Open the player crate menu");sender.sendMessage("§e/crates preview <crate> §7- Preview weighted rewards");sender.sendMessage("§e/crates open <crate> [virtual|physical] §7- Open a crate");sender.sendMessage("§e/crates claims [page] §7- Open durable claims");if(sender.hasPermission("plexoncrates.admin")){sender.sendMessage("§c/crates admin [create <id>] §7- GUI administration");sender.sendMessage("§c/crates link <crate> §7- Link the block you are looking at");sender.sendMessage("§c/crates unlink §7- Remove a physical block link");sender.sendMessage("§c/crates key <give|physical> <player> <crate> <amount>");sender.sendMessage("§c/crates reward add <crate> <weight> §7- Capture held exact item");sender.sendMessage("§c/crates reward remove <crate> <reward>");sender.sendMessage("§c/crates reward weight <crate> <reward> <weight>");sender.sendMessage("§c/crates reward action <crate> <reward> <ITEM|COMMAND|MESSAGE|SOUND> [value]");sender.sendMessage("§c/crates reload");}}
    @Override public @Nullable List<String> onTabComplete(@NotNull CommandSender sender,@NotNull Command command,@NotNull String alias,@NotNull String[] args){if(args.length==1){List<String> root=new ArrayList<>(List.of("preview","open","claims","help"));if(sender.hasPermission("plexoncrates.admin"))root.addAll(List.of("admin","link","unlink","key","reward","reload"));return filter(root,args[0]);}String sub=args[0].toLowerCase(Locale.ROOT);List<String> crateIds=plugin.crates().all().stream().map(Crate::id).toList();if(args.length==2&&List.of("preview","open","link").contains(sub))return filter(crateIds,args[1]);if(sub.equals("open")&&args.length==3)return filter(List.of("virtual","physical"),args[2]);if(sub.equals("admin")&&args.length==2)return filter(List.of("create"),args[1]);if(sub.equals("key")){if(args.length==2)return filter(List.of("give","physical"),args[1]);if(args.length==3)return filter(Bukkit.getOnlinePlayers().stream().map(Player::getName).toList(),args[2]);if(args.length==4)return filter(crateIds,args[3]);if(args.length==5)return filter(List.of("1","5","10","64"),args[4]);}if(sub.equals("reward")){if(args.length==2)return filter(List.of("add","remove","weight","action"),args[1]);if(args.length==3)return filter(crateIds,args[2]);if(args.length==4&&List.of("remove","weight","action").contains(args[1].toLowerCase(Locale.ROOT)))return plugin.crates().find(args[2]).map(crate->filter(crate.rewards().stream().map(reward->reward.id()).toList(),args[3])).orElse(List.of());if(args.length==4&&args[1].equalsIgnoreCase("add"))return filter(List.of("1","5","10","25","100"),args[3]);if(args.length==5&&args[1].equalsIgnoreCase("weight"))return filter(List.of("1","5","10","25","100"),args[4]);if(args.length==5&&args[1].equalsIgnoreCase("action"))return filter(List.of("ITEM","COMMAND","MESSAGE","SOUND"),args[4]);}return List.of();}
    private static List<String> filter(List<String> values,String prefix){String lower=prefix.toLowerCase(Locale.ROOT);return values.stream().filter(value->value.toLowerCase(Locale.ROOT).startsWith(lower)).sorted().toList();}
    private static final class CommandFailure extends RuntimeException{private CommandFailure(String message){super(message);}}
}
