package com.plexoncrates.manager;

import com.plexoncrates.config.ConfigManager;
import com.plexoncrates.core.PlexonCrates;
import com.plexoncrates.crate.Crate;
import com.plexoncrates.crate.Reward;
import com.plexoncrates.database.DatabaseManager;
import com.plexoncrates.util.ColorUtil;
import com.plexoncrates.util.ItemCodec;
import com.plexoncrates.util.WeightedSelector;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.logging.Level;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.inventory.ClickType;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.event.inventory.InventoryDragEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

public final class GUIManager {
    private static final int[] GRID={10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,37,38,39,40,41,42,43};
    private final PlexonCrates plugin;private final ConfigManager config;private final CrateManager crates;private final DatabaseManager database;
    private final Map<UUID,PlexonHolder> openMenus=new ConcurrentHashMap<>();
    public GUIManager(PlexonCrates plugin,ConfigManager config,CrateManager crates,DatabaseManager database){this.plugin=plugin;this.config=config;this.crates=crates;this.database=database;}

    public void openPlayerMenu(Player player){PlayerMenuHolder holder=new PlayerMenuHolder();Inventory inventory=create(holder,54,"&8PlexonCrates");decorateFrame(inventory);inventory.setItem(49,button(Material.ENDER_CHEST,"&6&lClaim Inbox",List.of("&7Collect rewards that did not fit","&7in your inventory.")));if(player.hasPermission("plexoncrates.admin.gui"))inventory.setItem(53,button(Material.COMPARATOR,"&c&lAdministration",List.of("&7Open crate management.")));renderPlayerCrates(player,holder,inventory,Map.of());open(player,holder,inventory);database.virtualKeys(player.getUniqueId()).whenComplete((balances,error)->runSync(()->{if(!player.isOnline()||player.getOpenInventory().getTopInventory().getHolder()!=holder)return;if(error!=null){plugin.getLogger().log(Level.WARNING,"Could not load virtual key balances",error);return;}renderPlayerCrates(player,holder,inventory,balances);}));}

    public void openPreview(Player player,Crate crate){openPreview(player,crate,0);}public void openPreview(Player player,Crate crate,int page){List<Reward> rewards=crate.rewards().stream().sorted(Comparator.comparing(Reward::id)).toList();int maxPage=Math.max(0,(rewards.size()-1)/45);int safePage=Math.max(0,Math.min(page,maxPage));PreviewHolder holder=new PreviewHolder(crate.id(),safePage);Inventory inventory=create(holder,54,crate.displayName()+" &8• Rewards");int start=safePage*45;for(int index=start;index<Math.min(rewards.size(),start+45);index++){Reward reward=rewards.get(index);int slot=index-start;holder.entries.put(slot,reward.id());inventory.setItem(slot,rewardIcon(reward,crate.rewards()));}inventory.setItem(45,button(Material.ARROW,"&ePrevious",List.of("&7Page "+(safePage+1))));inventory.setItem(49,button(Material.BARRIER,"&cBack",List.of("&7Return to crates.")));inventory.setItem(53,button(Material.ARROW,"&eNext",List.of("&7Page "+(safePage+1))));open(player,holder,inventory);}

    public void openAdmin(Player player){AdminHolder holder=new AdminHolder();Inventory inventory=create(holder,54,"&8PlexonCrates • Administration");decorateFrame(inventory);List<Crate> values=crates.all().stream().sorted(Comparator.comparing(Crate::id)).toList();for(int index=0;index<Math.min(GRID.length,values.size());index++){Crate crate=values.get(index);int slot=GRID[index];holder.entries.put(slot,crate.id());List<String> lore=new ArrayList<>();lore.add("&7ID: &f"+crate.id());lore.add("&7Status: "+(crate.enabled()?"&aEnabled":"&cDisabled"));lore.add("&7Rewards: &f"+crate.rewards().size());lore.add("&7Locations: &f"+crate.locations().size());lore.add("");lore.add("&eClick to edit");inventory.setItem(slot,icon(crate.icon(),crate.displayName(),lore));}inventory.setItem(49,button(Material.LIME_DYE,"&a&lCreate Crate",List.of("&7Creates a new editable crate","&7with an automatic safe ID.")));inventory.setItem(45,button(Material.ARROW,"&ePlayer Menu",List.of("&7Return to /crates.")));open(player,holder,inventory);}

    public void openCrateEditor(Player player,Crate crate){CrateEditorHolder holder=new CrateEditorHolder(crate.id());Inventory inventory=create(holder,27,"&8Edit • "+crate.id());fill(inventory,Material.GRAY_STAINED_GLASS_PANE);inventory.setItem(4,icon(crate.icon(),crate.displayName(),List.of("&7ID: &f"+crate.id(),"&7Locations: &f"+crate.locations().size())));inventory.setItem(10,button(crate.enabled()?Material.LIME_DYE:Material.GRAY_DYE,crate.enabled()?"&a&lEnabled":"&7&lDisabled",List.of("&eClick to toggle this crate.")));inventory.setItem(12,button(Material.CHEST,"&6&lRewards",List.of("&7Drag or shift-click exact items","&7into the reward editor.")));inventory.setItem(14,button(Material.CLOCK,"&b&lOpening Animation",List.of("&7Current: &f"+crate.animation(),"&eClick to cycle.")));inventory.setItem(16,button(Material.BLAZE_POWDER,"&d&lIdle Effect",List.of("&7Current: &f"+crate.idleEffect(),"&eClick to cycle.")));inventory.setItem(22,button(Material.ENDER_EYE,"&e&lPhysical Locations",List.of("&7Linked blocks: &f"+crate.locations().size(),"&7Look at a chest/barrel and use:","&f/crates link "+crate.id())));inventory.setItem(18,button(Material.ARROW,"&eBack",List.of("&7Return to administration.")));open(player,holder,inventory);}

    public void openRewardEditor(Player player,Crate crate){openRewardEditor(player,crate,0);}public void openRewardEditor(Player player,Crate crate,int page){List<Reward> rewards=crate.rewards().stream().sorted(Comparator.comparing(Reward::id)).toList();int maxPage=Math.max(0,(rewards.size()-1)/45);int safePage=Math.max(0,Math.min(page,maxPage));RewardEditorHolder holder=new RewardEditorHolder(crate.id(),safePage);Inventory inventory=create(holder,54,"&8Rewards • "+crate.id());int start=safePage*45;for(int index=start;index<Math.min(rewards.size(),start+45);index++){Reward reward=rewards.get(index);int slot=index-start;holder.entries.put(slot,reward.id());List<String> lore=new ArrayList<>();lore.add("&7Reward ID: &f"+reward.id());lore.add("&7Weight: &f"+reward.weight());lore.add(String.format(java.util.Locale.ROOT,"&7Chance: &e%.2f%%",WeightedSelector.chance(reward,crate.rewards())));lore.add("&7Actions: &f"+reward.actions().size());lore.add("");lore.add("&aLeft-click: +1 weight");lore.add("&aShift-left: +10 weight");lore.add("&cRight-click: -1 weight");lore.add("&cShift-right: -10 weight");lore.add("&4Drop key: remove reward");inventory.setItem(slot,icon(reward.displayItem(),null,lore));}inventory.setItem(45,button(Material.ARROW,"&ePrevious",List.of("&7Previous reward page.")));inventory.setItem(47,button(Material.HOPPER,"&a&lAdd Exact Item",List.of("&7Drag an item into an empty reward slot,","&7or shift-click it from your inventory.","&7The source item is never consumed.")));inventory.setItem(49,button(Material.ARROW,"&eBack",List.of("&7Return to crate editor.")));inventory.setItem(53,button(Material.ARROW,"&eNext",List.of("&7Next reward page.")));open(player,holder,inventory);}

    public void openClaims(Player player,int page){int safePage=Math.max(0,page);ClaimHolder holder=new ClaimHolder(safePage);Inventory inventory=create(holder,54,"&8Claim Inbox");fillBottomRow(inventory);inventory.setItem(49,button(Material.CLOCK,"&eLoading...",List.of("&7Reading durable claims.")));open(player,holder,inventory);int limit=config.claimPageSize();database.claims(player.getUniqueId(),limit,safePage*limit).whenComplete((claims,error)->runSync(()->{if(!player.isOnline()||player.getOpenInventory().getTopInventory().getHolder()!=holder)return;if(error!=null){plugin.getLogger().log(Level.WARNING,"Could not load claims",error);inventory.setItem(49,button(Material.BARRIER,"&cClaims unavailable",List.of()));return;}holder.claims.clear();for(int slot=0;slot<Math.min(45,claims.size());slot++){DatabaseManager.ClaimRecord claim=claims.get(slot);ItemStack item=ItemCodec.decodeBytes(claim.itemBytes());holder.claims.put(slot,claim);inventory.setItem(slot,icon(item,null,List.of("","&7Crate: &f"+claim.crateId(),"&7Reward: &f"+claim.rewardId(),"&eClick to claim")));}inventory.setItem(45,button(Material.ARROW,"&ePrevious",List.of()));inventory.setItem(49,button(Material.CHEST,"&6&lClaims",List.of("&7Page: &f"+(safePage+1),"&7Loaded: &f"+claims.size())));inventory.setItem(53,button(Material.ARROW,"&eNext",List.of()));}));}

    public Inventory createOpeningInventory(Player player,String title,int size){OpeningHolder holder=new OpeningHolder(player.getUniqueId());Inventory inventory=create(holder,size,title);openMenus.put(player.getUniqueId(),holder);return inventory;}

    public void handleClick(InventoryClickEvent event){if(!(event.getWhoClicked() instanceof Player player))return;Inventory top=event.getView().getTopInventory();if(!(top.getHolder() instanceof PlexonHolder holder))return;event.setCancelled(true);int raw=event.getRawSlot();if(holder instanceof OpeningHolder)return;if(holder instanceof PlayerMenuHolder menu){if(raw==49){openClaims(player,0);return;}if(raw==53&&player.hasPermission("plexoncrates.admin.gui")){openAdmin(player);return;}String crateId=menu.entries.get(raw);if(crateId==null)return;crates.find(crateId).ifPresent(crate->{if(event.isRightClick())plugin.openings().openVirtual(player,crate);else openPreview(player,crate);});return;}if(holder instanceof AdminHolder menu){if(raw==45){openPlayerMenu(player);return;}if(raw==49){Crate created=crates.createGenerated();openCrateEditor(player,created);return;}String crateId=menu.entries.get(raw);if(crateId!=null)crates.find(crateId).ifPresent(crate->openCrateEditor(player,crate));return;}if(holder instanceof CrateEditorHolder editor){Crate crate=crates.find(editor.crateId).orElse(null);if(crate==null){openAdmin(player);return;}if(raw==18)openAdmin(player);else if(raw==10){crates.toggleEnabled(crate.id());crates.find(crate.id()).ifPresent(updated->openCrateEditor(player,updated));}else if(raw==12)openRewardEditor(player,crate);else if(raw==14){crates.cycleAnimation(crate.id());crates.find(crate.id()).ifPresent(updated->openCrateEditor(player,updated));}else if(raw==16){crates.cycleIdleEffect(crate.id());crates.find(crate.id()).ifPresent(updated->openCrateEditor(player,updated));}return;}if(holder instanceof RewardEditorHolder editor){handleRewardEditorClick(player,event,editor);return;}if(holder instanceof PreviewHolder preview){Crate crate=crates.find(preview.crateId).orElse(null);if(crate==null)return;if(raw==45)openPreview(player,crate,preview.page-1);else if(raw==49)openPlayerMenu(player);else if(raw==53)openPreview(player,crate,preview.page+1);return;}if(holder instanceof ClaimHolder claims){if(raw==45){openClaims(player,claims.page-1);return;}if(raw==53){openClaims(player,claims.page+1);return;}DatabaseManager.ClaimRecord claim=claims.claims.get(raw);if(claim!=null)deliverClaim(player,claim,claims.page);}}

    public void handleDrag(InventoryDragEvent event){if(!(event.getWhoClicked() instanceof Player player))return;Inventory top=event.getView().getTopInventory();if(!(top.getHolder() instanceof PlexonHolder holder))return;event.setCancelled(true);if(!(holder instanceof RewardEditorHolder editor))return;boolean topRewardSlot=event.getRawSlots().stream().anyMatch(slot->slot>=0&&slot<45);ItemStack cursor=event.getOldCursor();if(topRewardSlot&&cursor!=null&&!cursor.getType().isAir())captureReward(player,editor.crateId,cursor);}
    public void handleClose(InventoryCloseEvent event){if(!(event.getPlayer() instanceof Player player))return;if(!(event.getInventory().getHolder() instanceof PlexonHolder holder))return;if(holder instanceof OpeningHolder&&config.lockOpeningInventory()&&plugin.animations().isOpening(player.getUniqueId())&&player.isOnline()){Bukkit.getScheduler().runTask(plugin,()->{if(player.isOnline()&&plugin.animations().isOpening(player.getUniqueId()))player.openInventory(holder.getInventory());});return;}openMenus.remove(player.getUniqueId(),holder);}

    private void handleRewardEditorClick(Player player,InventoryClickEvent event,RewardEditorHolder editor){Crate crate=crates.find(editor.crateId).orElse(null);if(crate==null)return;int raw=event.getRawSlot();if(raw==45){openRewardEditor(player,crate,editor.page-1);return;}if(raw==49){openCrateEditor(player,crate);return;}if(raw==53){openRewardEditor(player,crate,editor.page+1);return;}if(raw>=0&&raw<45){String rewardId=editor.entries.get(raw);if(rewardId!=null){if(event.getClick()==ClickType.DROP||event.getClick()==ClickType.CONTROL_DROP)crates.removeReward(crate.id(),rewardId);else if(event.isLeftClick())crates.adjustRewardWeight(crate.id(),rewardId,event.isShiftClick()?10:1);else if(event.isRightClick())crates.adjustRewardWeight(crate.id(),rewardId,event.isShiftClick()?-10:-1);crates.find(crate.id()).ifPresent(updated->openRewardEditor(player,updated,editor.page));return;}ItemStack cursor=event.getCursor();if(cursor!=null&&!cursor.getType().isAir()){captureReward(player,crate.id(),cursor);return;}}if(raw>=event.getView().getTopInventory().getSize()&&event.isShiftClick()){ItemStack clicked=event.getCurrentItem();if(clicked!=null&&!clicked.getType().isAir())captureReward(player,crate.id(),clicked);}}
    private void captureReward(Player player,String crateId,ItemStack source){try{crates.addCapturedReward(crateId,source.clone(),10);player.sendMessage(config.message("reward-added","item",source.getType().name(),"crate",crateId));crates.find(crateId).ifPresent(crate->openRewardEditor(player,crate));}catch(Exception error){player.sendMessage(config.prefix()+"§cCould not add reward: "+error.getMessage());}}
    private void deliverClaim(Player player,DatabaseManager.ClaimRecord claim,int page){ItemStack item=ItemCodec.decodeBytes(claim.itemBytes());if(!canFit(player.getInventory().getStorageContents(),item)){player.sendMessage(config.message("claim-blocked"));return;}database.deleteClaim(claim.id(),player.getUniqueId()).whenComplete((deleted,error)->runSync(()->{if(error!=null||!Boolean.TRUE.equals(deleted)){player.sendMessage(config.prefix()+"§cCould not finalize this claim.");return;}if(!player.isOnline()){database.queueClaim(player.getUniqueId(),claim.crateId(),claim.rewardId(),claim.itemBytes());return;}Map<Integer,ItemStack> leftovers=player.getInventory().addItem(item);if(!leftovers.isEmpty()){for(ItemStack leftover:leftovers.values())database.queueClaim(player.getUniqueId(),claim.crateId(),claim.rewardId(),ItemCodec.encodeBytes(leftover));player.sendMessage(config.message("claim-blocked"));}else player.sendMessage(config.message("claim-delivered"));openClaims(player,page);}));}

    private void renderPlayerCrates(Player player,PlayerMenuHolder holder,Inventory inventory,Map<String,Long> virtualBalances){holder.entries.clear();for(int slot:GRID)inventory.setItem(slot,null);List<Crate> values=crates.all().stream().filter(Crate::enabled).sorted(Comparator.comparing(Crate::id)).toList();for(int index=0;index<Math.min(values.size(),GRID.length);index++){Crate crate=values.get(index);int slot=GRID[index];holder.entries.put(slot,crate.id());List<String> lore=new ArrayList<>(crate.description());lore.add("");lore.add("&7Virtual keys: &f"+virtualBalances.getOrDefault(crate.id(),0L));lore.add("&7Physical keys: &f"+plugin.keys().countPhysical(player,crate));lore.add("&7Animation: &f"+crate.animation());lore.add("");lore.add("&eLeft-click to preview");lore.add("&aRight-click to open with a virtual key");inventory.setItem(slot,icon(crate.icon(),crate.displayName(),lore));}}
    private static boolean canFit(ItemStack[] storage,ItemStack item){int remaining=item.getAmount();for(ItemStack slot:storage){if(slot==null||slot.getType().isAir())remaining-=item.getMaxStackSize();else if(slot.isSimilar(item))remaining-=Math.max(0,slot.getMaxStackSize()-slot.getAmount());if(remaining<=0)return true;}return remaining<=0;}
    private Inventory create(PlexonHolder holder,int size,String title){Inventory inventory=Bukkit.createInventory(holder,size,ColorUtil.color(title));holder.bind(inventory);return inventory;}private void open(Player player,PlexonHolder holder,Inventory inventory){openMenus.put(player.getUniqueId(),holder);player.openInventory(inventory);}private static void decorateFrame(Inventory inventory){ItemStack pane=button(Material.GRAY_STAINED_GLASS_PANE,"&8",List.of());for(int slot=0;slot<inventory.getSize();slot++){int column=slot%9;if(slot<9||slot>=inventory.getSize()-9||column==0||column==8)inventory.setItem(slot,pane);}}private static void fillBottomRow(Inventory inventory){ItemStack pane=button(Material.GRAY_STAINED_GLASS_PANE,"&8",List.of());for(int slot=45;slot<54;slot++)inventory.setItem(slot,pane);}private static void fill(Inventory inventory,Material material){ItemStack pane=button(material,"&8",List.of());for(int slot=0;slot<inventory.getSize();slot++)inventory.setItem(slot,pane);}private static ItemStack rewardIcon(Reward reward,Collection<Reward> all){return icon(reward.displayItem(),null,List.of("","&7Weight: &f"+reward.weight(),String.format(java.util.Locale.ROOT,"&7Chance: &e%.2f%%",WeightedSelector.chance(reward,all)),"&7Actions: &f"+reward.actions().size()));}private static ItemStack button(Material material,String name,List<String> lore){return icon(new ItemStack(material),name,lore);}private static ItemStack icon(ItemStack source,String overrideName,List<String> extraLore){ItemStack item=source.clone();ItemMeta meta=item.getItemMeta();if(overrideName!=null)meta.setDisplayName(ColorUtil.color(overrideName));List<String> lore=meta.hasLore()?new ArrayList<>(meta.getLore()):new ArrayList<>();if(extraLore!=null)for(String line:extraLore)lore.add(ColorUtil.color(line));if(!lore.isEmpty())meta.setLore(lore);item.setItemMeta(meta);return item;}private void runSync(Runnable action){if(!plugin.isEnabled())return;if(Bukkit.isPrimaryThread())action.run();else Bukkit.getScheduler().runTask(plugin,action);}

    public abstract static class PlexonHolder implements InventoryHolder{private Inventory inventory;private void bind(Inventory inventory){this.inventory=inventory;}@Override public Inventory getInventory(){return inventory;}}
    public static final class OpeningHolder extends PlexonHolder{private final UUID playerId;public OpeningHolder(UUID playerId){this.playerId=playerId;}public UUID playerId(){return playerId;}}
    private static final class PlayerMenuHolder extends PlexonHolder{private final Map<Integer,String> entries=new LinkedHashMap<>();}
    private static final class AdminHolder extends PlexonHolder{private final Map<Integer,String> entries=new LinkedHashMap<>();}
    private static final class CrateEditorHolder extends PlexonHolder{private final String crateId;private CrateEditorHolder(String crateId){this.crateId=crateId;}}
    private static final class RewardEditorHolder extends PlexonHolder{private final String crateId;private final int page;private final Map<Integer,String> entries=new LinkedHashMap<>();private RewardEditorHolder(String crateId,int page){this.crateId=crateId;this.page=page;}}
    private static final class PreviewHolder extends PlexonHolder{private final String crateId;private final int page;private final Map<Integer,String> entries=new LinkedHashMap<>();private PreviewHolder(String crateId,int page){this.crateId=crateId;this.page=page;}}
    private static final class ClaimHolder extends PlexonHolder{private final int page;private final Map<Integer,DatabaseManager.ClaimRecord> claims=new LinkedHashMap<>();private ClaimHolder(int page){this.page=page;}}
}
