package com.antondev.crates.service;

import com.antondev.crates.PlexonCrates;
import com.antondev.crates.database.DatabaseService;
import com.antondev.crates.model.Crate;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicReference;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.persistence.PersistentDataType;

/**
 * Issues and verifies administrator-created portable crate items.
 *
 * <p>The HMAC secret is loaded or generated by the SQLite worker. Item metadata
 * is only an untrusted transport envelope; opening code must still validate the
 * durable issuance row and published runtime revision before consuming it.</p>
 */
public final class PortableCrateService {
    public static final int MAX_BATCH = 64;
    private static final String SECRET_ID = "portable-hmac-v1";

    private final PlexonCrates plugin;
    private final NamespacedKey marker;
    private final NamespacedKey schema;
    private final NamespacedKey tokenKey;
    private final AtomicReference<byte[]> secret = new AtomicReference<>();
    private volatile CompletableFuture<byte[]> secretLoad = CompletableFuture.failedFuture(
            new IllegalStateException("Portable signing secret has not started"));

    public PortableCrateService(PlexonCrates plugin) {
        this.plugin = Objects.requireNonNull(plugin, "plugin");
        marker = new NamespacedKey(plugin, "portable_crate");
        schema = new NamespacedKey(plugin, "portable_crate_schema");
        tokenKey = new NamespacedKey(plugin, "portable_crate_token");
    }

    /** Starts one durable secret load/generation operation during plugin enable. */
    public void start() {
        secretLoad = plugin.database().loadOrCreatePortableSecret().thenApply(value -> {
            byte[] copy = value.clone();
            secret.set(copy);
            return copy.clone();
        });
        secretLoad.whenComplete((ignored, error) -> {
            if (error != null) {
                plugin.getLogger().log(java.util.logging.Level.SEVERE,
                        "Portable crate signing secret is unavailable; portable issuance is disabled. "
                                + "No automatic rotation will be attempted.", error);
            }
        });
    }

    public boolean ready() {
        return secret.get() != null;
    }

    public CompletableFuture<Boolean> secretPresent() {
        return plugin.database().portableSecretPresent();
    }

    public String secretId() {
        return SECRET_ID;
    }

    /**
     * Creates and durably records one unused issuance before returning its item.
     * No Bukkit state is mutated by this method.
     */
    public CompletableFuture<ItemStack> issue(
            Crate crate, PortableCrateCodec.RevisionPolicy policy, long pinnedRevision,
            UUID issuedTo, UUID issuedBy) {
        Objects.requireNonNull(crate, "crate");
        Objects.requireNonNull(policy, "policy");
        if (crate.state() != com.antondev.crates.domain.crate.CrateState.PUBLISHED) {
            throw new IllegalArgumentException("Portable crates require a published crate");
        }
        if (policy == PortableCrateCodec.RevisionPolicy.PINNED_REVISION
                && pinnedRevision != plugin.runtime().crateRevision(crate.id())) {
            throw new IllegalArgumentException("Pinned portable revision must match the retained published revision");
        }
        if (policy == PortableCrateCodec.RevisionPolicy.LATEST_PUBLISHED) pinnedRevision = 0;
        final long revision = pinnedRevision;
        return secretLoad.thenCompose(key -> {
            PortableCrateCodec.Token token = PortableCrateCodec.issue(
                    crate.id(), policy, revision, issuedTo, key);
            Instant now = Instant.now();
            DatabaseService.PortableIssue record = new DatabaseService.PortableIssue(
                    token.payload().issueId(), token.payload().crateId(), policy.name(), revision,
                    issuedTo, issuedBy, PortableCrateCodec.VERSION, "UNUSED", null, now, now);
            return plugin.database().createPortableIssue(record)
                    .thenApply(ignored -> createItem(crate, token));
        });
    }

    /** Creates a bounded batch of distinct single-use items. */
    public CompletableFuture<List<ItemStack>> issueBatch(
            Crate crate, PortableCrateCodec.RevisionPolicy policy, long pinnedRevision,
            UUID issuedTo, UUID issuedBy, int amount) {
        if (amount < 1 || amount > MAX_BATCH) {
            throw new IllegalArgumentException("Portable issuance amount must be between 1 and " + MAX_BATCH);
        }
        var futures = new ArrayList<CompletableFuture<ItemStack>>(amount);
        for (int index = 0; index < amount; index++) {
            futures.add(issue(crate, policy, pinnedRevision, issuedTo, issuedBy));
        }
        return CompletableFuture.allOf(futures.toArray(CompletableFuture[]::new))
                .thenApply(ignored -> futures.stream().map(CompletableFuture::join).toList());
    }

    /** Builds a display item with only server-owned portable metadata. */
    public ItemStack createItem(Crate crate, PortableCrateCodec.Token token) {
        Objects.requireNonNull(crate, "crate");
        Objects.requireNonNull(token, "token");
        if (!crate.id().equals(token.payload().crateId())) {
            throw new IllegalArgumentException("Portable token crate does not match its display crate");
        }
        ItemStack item = new ItemStack(Material.CHEST);
        item.editMeta(meta -> {
            meta.displayName(com.antondev.crates.config.Text.parse(
                    "<gradient:#DDE5F0:#A3BEDF><bold>Portable Crate</bold></gradient> <dark_gray>•</dark_gray> <white>"
                            + crate.id() + "</white>"));
            meta.lore(List.of(
                    com.antondev.crates.config.Text.parse("<gray>Right-click to preview and open this published crate.</gray>"),
                    com.antondev.crates.config.Text.parse("<dark_gray>Single-use · authentic server issuance</dark_gray>")));
            var pdc = meta.getPersistentDataContainer();
            pdc.set(marker, PersistentDataType.BYTE, (byte) 1);
            pdc.set(schema, PersistentDataType.INTEGER, PortableCrateCodec.VERSION);
            pdc.set(tokenKey, PersistentDataType.STRING, token.encoded());
        });
        return item;
    }

    public boolean isPortable(ItemStack item) {
        if (item == null || item.getType().isAir() || !item.hasItemMeta()) return false;
        var pdc = item.getItemMeta().getPersistentDataContainer();
        return pdc.has(marker, PersistentDataType.BYTE)
                && pdc.getOrDefault(schema, PersistentDataType.INTEGER, 0) == PortableCrateCodec.VERSION
                && pdc.has(tokenKey, PersistentDataType.STRING);
    }

    /** Verifies the envelope signature without touching the database. */
    public Optional<PortableCrateCodec.Token> decode(ItemStack item) {
        if (!isPortable(item) || !ready()) return Optional.empty();
        String encoded = item.getItemMeta().getPersistentDataContainer()
                .get(tokenKey, PersistentDataType.STRING);
        try {
            return Optional.of(PortableCrateCodec.decodeAndVerify(encoded, secret.get()));
        } catch (RuntimeException invalid) {
            return Optional.empty();
        }
    }

    /** Verifies the envelope and compares it with the durable issuance row. */
    public CompletableFuture<Optional<DatabaseService.PortableIssue>> verify(ItemStack item) {
        Optional<PortableCrateCodec.Token> decoded = decode(item);
        if (decoded.isEmpty()) return CompletableFuture.completedFuture(Optional.empty());
        PortableCrateCodec.Payload payload = decoded.get().payload();
        return plugin.database().loadPortableIssue(payload.issueId()).thenApply(row -> row.filter(issue ->
                issue.crateId().equals(payload.crateId())
                        && issue.revisionPolicy().equals(payload.revisionPolicy().name())
                        && issue.pinnedRevision() == payload.pinnedRevision()
                        && Objects.equals(issue.issuedTo(), payload.issuedTo())
                        && issue.signatureVersion() == PortableCrateCodec.VERSION));
    }

    /** Returns a stable token string only for an authentic item. */
    public Optional<String> encoded(ItemStack item) {
        return decode(item).map(PortableCrateCodec.Token::encoded);
    }

    /** Removes exactly one item from a main-hand stack after external validation. */
    public static boolean consumeOne(Player player, ItemStack expected) {
        Objects.requireNonNull(player, "player");
        Objects.requireNonNull(expected, "expected");
        ItemStack held = player.getInventory().getItemInMainHand();
        if (!held.isSimilar(expected) || held.getAmount() < 1) return false;
        if (held.getAmount() == 1) player.getInventory().setItemInMainHand(new ItemStack(Material.AIR));
        else held.setAmount(held.getAmount() - 1);
        return true;
    }
}
