package com.antondev.crates.service;

import com.antondev.crates.PlexonCrates;
import com.antondev.crates.database.DatabaseService;
import com.antondev.crates.model.Crate;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicReference;
import java.util.concurrent.atomic.LongAdder;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.persistence.PersistentDataType;

/**
 * Issues and verifies administrator-created portable crate items.
 *
 * <p>The HMAC secret is loaded or generated by the SQLite worker. Item metadata
 * is only an untrusted transport envelope; opening code must still validate the
 * durable issuance row and published runtime revision before consuming it.</p>
 */
public final class PortableCrateService {
    public static final int MAX_BATCH = 64;
    private static final String SECRET_ID = "portable-hmac-v1";

    private final PlexonCrates plugin;
    private final NamespacedKey marker;
    private final NamespacedKey schema;
    private final NamespacedKey tokenKey;
    private final AtomicReference<byte[]> secret = new AtomicReference<>();
    private final LongAdder materialFastRejects = new LongAdder();
    private final LongAdder metadataAcquisitions = new LongAdder();
    private final LongAdder envelopeHits = new LongAdder();
    private final LongAdder malformedIdentities = new LongAdder();
    private final LongAdder durableVerificationAttempts = new LongAdder();
    private volatile CompletableFuture<byte[]> secretLoad = CompletableFuture.failedFuture(
            new IllegalStateException("Portable signing secret has not started"));

    public PortableCrateService(PlexonCrates plugin) {
        this.plugin = Objects.requireNonNull(plugin, "plugin");
        marker = new NamespacedKey(plugin, "portable_crate");
        schema = new NamespacedKey(plugin, "portable_crate_schema");
        tokenKey = new NamespacedKey(plugin, "portable_crate_token");
    }

    /** Recovers interrupted reservations, then starts one durable secret load during plugin enable. */
    public void start() {
        secretLoad = plugin.database().recoverPortableReservations().thenCompose(recovered -> {
            if (recovered > 0) {
                plugin.getLogger().warning("Released " + recovered
                        + " interrupted portable-crate reservation"
                        + (recovered == 1 ? "" : "s") + "; no portable items were consumed.");
            }
            return plugin.database().loadOrCreatePortableSecret();
        }).thenApply(value -> {
            byte[] copy = value.clone();
            secret.set(copy);
            return copy.clone();
        });
        secretLoad.whenComplete((ignored, error) -> {
            if (error != null) {
                plugin.getLogger().log(java.util.logging.Level.SEVERE,
                        "Portable crate signing secret is unavailable; portable issuance is disabled. "
                                + "No automatic rotation will be attempted.", error);
            }
        });
    }

    public boolean ready() {
        return secret.get() != null;
    }

    public CompletableFuture<Boolean> secretPresent() {
        return plugin.database().portableSecretPresent();
    }

    public String secretId() {
        return SECRET_ID;
    }

    /**
     * Creates and durably records one unused issuance before returning its item.
     * No Bukkit state is mutated by this method.
     */
    public CompletableFuture<ItemStack> issue(
            Crate crate, PortableCrateCodec.RevisionPolicy policy, long pinnedRevision,
            UUID issuedTo, UUID issuedBy) {
        Objects.requireNonNull(crate, "crate");
        Objects.requireNonNull(policy, "policy");
        if (crate.state() != com.antondev.crates.domain.crate.CrateState.PUBLISHED) {
            throw new IllegalArgumentException("Portable crates require a published crate");
        }
        if (policy == PortableCrateCodec.RevisionPolicy.PINNED_REVISION
                && pinnedRevision != plugin.runtime().crateRevision(crate.id())) {
            throw new IllegalArgumentException("Pinned portable revision must match the retained published revision");
        }
        if (policy == PortableCrateCodec.RevisionPolicy.LATEST_PUBLISHED) pinnedRevision = 0;
        final long revision = pinnedRevision;
        return secretLoad.thenCompose(key -> {
            PortableCrateCodec.Token token = PortableCrateCodec.issue(
                    crate.id(), policy, revision, issuedTo, key);
            Instant now = Instant.ofEpochMilli(System.currentTimeMillis());
            DatabaseService.PortableIssue record = new DatabaseService.PortableIssue(
                    token.payload().issueId(), token.payload().crateId(), policy.name(), revision,
                    issuedTo, issuedBy, PortableCrateCodec.VERSION, "UNUSED", null, now, now);
            return plugin.database().createPortableIssue(record)
                    .thenApply(ignored -> createItem(crate, token));
        });
    }

    /** Creates a bounded batch of distinct single-use items. */
    public CompletableFuture<List<ItemStack>> issueBatch(
            Crate crate, PortableCrateCodec.RevisionPolicy policy, long pinnedRevision,
            UUID issuedTo, UUID issuedBy, int amount) {
        if (amount < 1 || amount > MAX_BATCH) {
            throw new IllegalArgumentException("Portable issuance amount must be between 1 and " + MAX_BATCH);
        }
        var futures = new ArrayList<CompletableFuture<ItemStack>>(amount);
        for (int index = 0; index < amount; index++) futures.add(issue(crate, policy, pinnedRevision, issuedTo, issuedBy));
        return CompletableFuture.allOf(futures.toArray(CompletableFuture[]::new))
                .thenApply(ignored -> futures.stream().map(CompletableFuture::join).toList());
    }

    /** Builds a display item with only server-owned portable metadata. */
    public ItemStack createItem(Crate crate, PortableCrateCodec.Token token) {
        Objects.requireNonNull(crate, "crate");
        Objects.requireNonNull(token, "token");
        if (!crate.id().equals(token.payload().crateId())) {
            throw new IllegalArgumentException("Portable token crate does not match its display crate");
        }
        ItemStack item = new ItemStack(Material.CHEST);
        item.editMeta(meta -> {
            meta.displayName(com.antondev.crates.config.Text.parse(
                    "<gradient:#DDE5F0:#A3BEDF><bold>Portable Crate</bold></gradient> <dark_gray>•</dark_gray> <white>"
                            + crate.id() + "</white>"));
            meta.lore(List.of(
                    com.antondev.crates.config.Text.parse("<gray>Right-click to preview and open this published crate.</gray>"),
                    com.antondev.crates.config.Text.parse("<dark_gray>Single-use · authentic server issuance</dark_gray>")));
            var pdc = meta.getPersistentDataContainer();
            pdc.set(marker, PersistentDataType.BYTE, (byte) 1);
            pdc.set(schema, PersistentDataType.INTEGER, PortableCrateCodec.VERSION);
            pdc.set(tokenKey, PersistentDataType.STRING, token.encoded());
        });
        return item;
    }

    /** Cheap envelope-only identification. It never authenticates issuance. */
    public boolean isPortable(ItemStack item) {
        return inspectEnvelope(item).isPresent();
    }

    /**
     * Performs the complete synchronous item inspection exactly once. The
     * portable flag only means a structurally valid Crates envelope was found;
     * the optional token is present only when HMAC verification also succeeds.
     */
    public Inspection inspect(ItemStack item) {
        Optional<PortableEnvelope> envelope = inspectEnvelope(item);
        if (envelope.isEmpty()) return Inspection.notPortable();
        byte[] key = secret.get();
        if (key == null) return new Inspection(true, Optional.empty());
        try {
            return new Inspection(true, Optional.of(PortableCrateCodec.decodeAndVerify(envelope.get().encodedToken(), key)));
        } catch (RuntimeException invalid) {
            malformedIdentities.increment();
            return new Inspection(true, Optional.empty());
        }
    }

    /** Verifies the envelope signature without touching the database. */
    public Optional<PortableCrateCodec.Token> decode(ItemStack item) {
        return inspect(item).token();
    }

    /** Verifies an already-inspected token against the durable issuance row. */
    public CompletableFuture<Optional<DatabaseService.PortableIssue>> verify(Inspection inspection) {
        Objects.requireNonNull(inspection, "inspection");
        if (!inspection.portable() || inspection.token().isEmpty()) {
            return CompletableFuture.completedFuture(Optional.empty());
        }
        durableVerificationAttempts.increment();
        PortableCrateCodec.Payload payload = inspection.token().get().payload();
        return plugin.database().loadPortableIssue(payload.issueId()).thenApply(row -> row.filter(issue ->
                issue.crateId().equals(payload.crateId())
                        && issue.revisionPolicy().equals(payload.revisionPolicy().name())
                        && issue.pinnedRevision() == payload.pinnedRevision()
                        && Objects.equals(issue.issuedTo(), payload.issuedTo())
                        && issue.signatureVersion() == PortableCrateCodec.VERSION));
    }

    /** Backward-compatible verification entry point for non-listener callers. */
    public CompletableFuture<Optional<DatabaseService.PortableIssue>> verify(ItemStack item) {
        return verify(inspect(item));
    }

    /** Returns a stable token string only for an authentic item. */
    public Optional<String> encoded(ItemStack item) {
        return decode(item).map(PortableCrateCodec.Token::encoded);
    }

    public Diagnostics diagnostics() {
        return new Diagnostics(materialFastRejects.sum(), metadataAcquisitions.sum(), envelopeHits.sum(),
                malformedIdentities.sum(), durableVerificationAttempts.sum());
    }

    /** Removes exactly one item from a main-hand stack after external validation. */
    public static boolean consumeOne(Player player, ItemStack expected) {
        Objects.requireNonNull(player, "player");
        Objects.requireNonNull(expected, "expected");
        ItemStack held = player.getInventory().getItemInMainHand();
        if (!held.isSimilar(expected) || held.getAmount() < 1) return false;
        if (held.getAmount() == 1) player.getInventory().setItemInMainHand(new ItemStack(Material.AIR));
        else held.setAmount(held.getAmount() - 1);
        return true;
    }

    private Optional<PortableEnvelope> inspectEnvelope(ItemStack item) {
        if (item == null || item.getType() != Material.CHEST || !item.hasItemMeta()) {
            materialFastRejects.increment();
            return Optional.empty();
        }
        metadataAcquisitions.increment();
        var pdc = item.getItemMeta().getPersistentDataContainer();
        if (!pdc.has(marker, PersistentDataType.BYTE)
                || pdc.getOrDefault(schema, PersistentDataType.INTEGER, 0) != PortableCrateCodec.VERSION) {
            return Optional.empty();
        }
        String encoded = pdc.get(tokenKey, PersistentDataType.STRING);
        if (encoded == null || encoded.isBlank()) {
            malformedIdentities.increment();
            return Optional.empty();
        }
        envelopeHits.increment();
        return Optional.of(new PortableEnvelope(PortableCrateCodec.VERSION, encoded));
    }

    private record PortableEnvelope(int schema, String encodedToken) {}

    public record Inspection(boolean portable, Optional<PortableCrateCodec.Token> token) {
        public Inspection {
            token = token == null ? Optional.empty() : token;
        }

        public static Inspection notPortable() {
            return new Inspection(false, Optional.empty());
        }
    }

    public record Diagnostics(long materialFastRejects, long metadataAcquisitions, long envelopeHits,
                              long malformedIdentities, long durableVerificationAttempts) {}
}
